name: Nuxt CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/web.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      - name: Build App
        working-directory: ./web
        run: | 
          npm run build
          tar -czf .output.tar.gz .output

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./web/.output.tar.gz
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      ROOT_DIR: /var/www/pigment
      APP_DIR: /var/www/pigment/web
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      RELEASE_DIR: /var/www/pigment/web/releases/${{ github.sha }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          
      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: output.tar.gz
          target: /var/www/pigment/web/releases/${{ github.sha }}

      - name: Symlink and Reload PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ROOT_DIR,RELEASE_DIR,APP_DIR
          script: |
            export ROOT_DIR=$ROOT_DIR
            export RELEASE_DIR=$RELEASE_DIR
            tar -xzf $RELEASE_DIR/output.tar.gz
            rm -rf /var/www/pigment/web/current
            ln -s $RELEASE_DIR /var/www/pigment/web/current
            cd /var/www/pigment/web/current
            pm2 reload ecosystem.config.js --env production